### ISSUE TITLE
Show stderr

### ISSUE THREAD

**Issue by buob** [willdurand/hubot-ansible#1]
Thanks for this script, helpful for me to see an example as a newbie to hubot. 👍 

I'm not getting the stdout, could this be a difference with node 4?  (I don't use node often, but when I do, it's progressed several major versions and all of the tooling has broken 😁 )

Thanks again!

**Comment by willdurand** [comment]
Hi! Do you have `shelljs` installed? I am not sure why you don't have any output at first glance..

**Comment by buob** [comment]
I'm seeing it in the `node_modules` folder, and hubot is loading (which I'm guessing it wouldn't boot if it couldn't resolve the requires? but perhaps not).

This could be a problem with running the commands in general, I haven't been able to run the command successfully yet either.  I got it working with plain node child_process, which I'm assuming isn't as portable.

Will post an update if/when I know more.

**Comment by buob** [comment]
Updated the issue -- it was just swallowing the failure.  I'll submit a PR for this soon.

**Comment by willdurand** [comment]
Merged your PR, thank you!
